import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from '@react-pdf/renderer'
import type { Assignment } from '../types'

Font.register({
  family: 'Helvetica',
  src: 'https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZ9hiA.woff2',
})

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: 'Helvetica',
    color: '#1a1a1a',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 4,
  },
  headerSub: {
    fontSize: 13,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 2,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
    marginBottom: 8,
  },
  bold: {
    fontWeight: 'bold',
  },
  generalInstruction: {
    fontWeight: 'bold',
    marginBottom: 12,
  },
  infoLine: {
    marginBottom: 4,
    fontSize: 11,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
    marginTop: 16,
    marginBottom: 10,
  },
  sectionType: {
    fontWeight: 'bold',
    fontSize: 11,
    marginBottom: 2,
  },
  sectionInstruction: {
    fontSize: 10,
    color: '#555',
    fontStyle: 'italic',
    marginBottom: 8,
  },
  question: {
    flexDirection: 'row',
    marginBottom: 6,
    paddingLeft: 8,
  },
  qNumber: {
    width: 24,
    textAlign: 'right',
    marginRight: 6,
  },
  qText: {
    flex: 1,
    lineHeight: 1.5,
  },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
    marginTop: 12,
    marginBottom: 8,
  },
  endText: {
    fontWeight: 'bold',
    marginTop: 8,
  },
  answerKeyTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    marginTop: 20,
    marginBottom: 10,
  },
  footer: {
    position: 'absolute',
    bottom: 20,
    left: 40,
    right: 40,
    textAlign: 'center',
    fontSize: 8,
    color: '#999',
  },
})

const getDifficultyLabel = (d: string) => {
  if (d === 'easy') return 'Easy'
  if (d === 'moderate') return 'Moderate'
  return 'Challenging'
}

const PdfDocument = ({ assignment }: { assignment: Assignment }) => {
  const output = assignment.output

  if (!output) return null

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <Text style={styles.headerTitle}>Delhi Public School, Sector-4, Bokaro</Text>
        <Text style={styles.headerSub}>Subject: {assignment.title}</Text>
        <Text style={styles.headerSub}>Class: 5th</Text>

        {/* Time + Marks */}
        <View style={styles.row}>
          <Text style={styles.bold}>Time Allowed: 45 minutes</Text>
          <Text style={styles.bold}>Maximum Marks: {output.totalMarks}</Text>
        </View>

        {/* General Instruction */}
        <Text style={styles.generalInstruction}>
          All questions are compulsory unless stated otherwise.
        </Text>

        {/* Student Info */}
        <Text style={styles.infoLine}>Name: _________________________</Text>
        <Text style={styles.infoLine}>Roll Number: __________________</Text>
        <Text style={styles.infoLine}>Class: 5th Section: ___________</Text>

        {/* Sections */}
        {output.sections.map((section, sIdx) => (
          <View key={sIdx}>
            <Text style={styles.sectionTitle}>{section.title}</Text>
            <Text style={styles.sectionType}>{section.questionType}</Text>
            <Text style={styles.sectionInstruction}>
              {section.instruction}. Each question carries {section.questions[0]?.marks} marks
            </Text>

            {section.questions.map((q) => (
              <View key={q.questionNumber} style={styles.question}>
                <Text style={styles.qNumber}>{q.questionNumber}.</Text>
                <Text style={styles.qText}>
                  [{getDifficultyLabel(q.difficulty)}] {q.text} [{q.marks} Marks]
                </Text>
              </View>
            ))}
          </View>
        ))}

        {/* End */}
        <View style={styles.divider} />
        <Text style={styles.endText}>End of Question Paper</Text>

        {/* Footer */}
        <Text style={styles.footer}>Generated by VedaAI</Text>
      </Page>
    </Document>
  )
}

export default PdfDocument